#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
>&2 echo 'Ran database migrations...'

python /app/manage.py collectstatic --noinput
>&2 echo 'Collected static files...'

>&2 echo 'About to run Gunicorn...'
gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 600 --chdir=/app
