name: build and push

on:
    push:
      branches:
        - "develop"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -
                name: Get Current Version
                run: |
                    echo "VERSION=`python version.py`" >> "$GITHUB_ENV"

            -
                name: Build and Push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./Dockerfile
                    push: True
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/onboarding-${{ vars.TEST_ENVIRONMENT }}:${{ env.VERSION }}
                    secrets: |
                        "SECRET_KEY=${{ secrets.TEST_SECRET_KEY }}"
                        "DEBUG=${{ vars.TEST_DEBUG }}"
                        "ENVIRONMENT=${{ vars.TEST_ENVIRONMENT }}"
                        "SENTRY_DSN: ${{ secrets.TEST_SENTRY_DSN }}"
                        "PORT: ${{ vars.TEST_PORT }}"
                        "AWS_SES_REGION_NAME: ${{ vars.TEST_AWS_SES_REGION_NAME }}"
                        "AWS_SES_REGION_ENDPOINT: ${{ secrets.TEST_AWS_SES_REGION_ENDPOINT }}"
                        "AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}"
                        "AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}"
                        "AWS_SES_FROM_EMAIL: ${{ vars.TEST_AWS_SES_FROM_EMAIL }}"
