name: Lint and Test

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Test
        env:
          SECRET_KEY: "very-SECRET-key"
          DEBUG: True
        run: |
          tox -r