name: Lint and Test

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          DEBUG: ${{ vars.DEBUG }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          AWS_SES_REGION_NAME: ${{ vars.AWS_SES_REGION_NAME }}
          AWS_SES_REGION_ENDPOINT: ${{ secrets.AWS_SES_REGION_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SES_FROM_EMAIL: ${{ vars.AWS_SES_FROM_EMAIL }}
        run: |
          tox -r